-- ============================================================
-- PLEDGE CARD GENERATOR
-- SUPABASE DATABASE SETUP
-- ============================================================

create table if not exists public.templates (
    id bigint generated by default as identity primary key,

    image_url text not null,

    width integer not null,

    height integer not null,

    area jsonb not null default
        '{"xPct":25,"yPct":25,"wPct":50,"hPct":50}'::jsonb,

    shape text not null default 'rect',

    radius_pct numeric not null default 18,

    fit text not null default 'cover',

    published boolean not null default false,

    updated_at timestamptz not null default now()
);


-- ============================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================

alter table public.templates
enable row level security;


-- ============================================================
-- PUBLIC USERS
-- Can only see published templates.
-- ============================================================

drop policy if exists
"Public can view published templates"
on public.templates;

create policy
"Public can view published templates"
on public.templates

for select

to anon

using (
    published = true
);


-- ============================================================
-- LOGGED-IN ADMIN
-- Can view templates.
-- ============================================================

drop policy if exists
"Authenticated users can view templates"
on public.templates;

create policy
"Authenticated users can view templates"
on public.templates

for select

to authenticated

using (
    true
);


-- ============================================================
-- ADMIN INSERT
-- ============================================================

drop policy if exists
"Authenticated users can insert templates"
on public.templates;

create policy
"Authenticated users can insert templates"

on public.templates

for insert

to authenticated

with check (
    true
);


-- ============================================================
-- ADMIN UPDATE
-- ============================================================

drop policy if exists
"Authenticated users can update templates"
on public.templates;

create policy
"Authenticated users can update templates"

on public.templates

for update

to authenticated

using (
    true
)

with check (
    true
);


-- ============================================================
-- ADMIN DELETE
-- ============================================================

drop policy if exists
"Authenticated users can delete templates"
on public.templates;

create policy
"Authenticated users can delete templates"

on public.templates

for delete

to authenticated

using (
    true
);